# Generated by Django 5.1.1 on 2024-09-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycontacts', '0002_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('name',)},
        ),
    ]
